language: node_js
node_js:
  - "node"
  - "10"
  - "8"
cache: npm
os:
  - osx
  - precise
  - xenial
  - windows
script:
  - npm test
notifications:
  email:
    on_success: never
    on_failure: always
